controller:
  clusterName: terraform-eks-cluster

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::504122215048:role/AmazonEKSLoadBalancerControllerRole
  name: aws-load-balancer-controller

ingress:
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: public-alb-terraform-eks-cluster
    alb.ingress.kubernetes.io/group.name: public-1
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:504122215048:certificate/9f1685ff-767a-44b4-a74f-e775b54bd40b