storageClasses:
- name: efs-sc
  annotations:
    # Use that annotation if you want this to your default storageclass
    storageclass.kubernetes.io/is-default-class: "true"
  mountOptions:
  - tls
  parameters:
    provisioningMode: efs-ap
    fileSystemId: fs-007afd3b811a74727
    directoryPerms: "700"
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
