replicaCount: 1

image:
  repository: ofekmalul/web-app-for-argocd
  pullPolicy: IfNotPresent
  tag: "1.0.1"

myLabel: 'web-app'

service:
  name: web-app-service
  type: ClusterIP
  port: 9090
  targetPort: 9090
