{{- range .Values.apps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: {{ .namespace_argo }}
spec: 
  project: {{ .project }}
  source:
    repoURL: {{ .repoURL }}
    targetRevision: {{ .targetRevision }}
    path: {{ .path }}
  destination:
    server: {{ .server }}
    namespace: {{ .namespace }}
  syncPolicy:
    automated:
      selfHeal: {{ .selfHeal }}
      prune: {{ .prune }}
{{- end }}